pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                dir('test-monorepo-foo') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('test-monorepo-foo') {
                    sh 'mvn test'
                }
            }
            post {
                dir('test-monorepo-foo') {
                    always {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('Deliver') { 
            steps {
                dir('test-monorepo-foo') {
                    sh 'echo test' 
                }
            }
        }
    }
}