String validateFileChange() {
    for(changeSet in currentBuild.changeSets) {
        for(entry in changeSet.getItems()) {
            for(file in entry.getAffectedFiles()) {
                print 'hello'
            }
        }
    }
}

pipeline {
    agent any

    stages {
        stage('Validate File Change') { 
            steps {
                echo validateFileChange()
            }
        }
    }
}